/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ItemCategory = "creator" | "other" | "parts" | "tools" | "utility";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type RequestStatus = "closed" | "matched" | "open";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface GeographyColumns {
  coordDimension: number | null;
  fGeographyColumn: string | null;
  fTableCatalog: string | null;
  fTableName: string | null;
  fTableSchema: string | null;
  srid: number | null;
  type: string | null;
}

export interface GeometryColumns {
  coordDimension: number | null;
  fGeometryColumn: string | null;
  fTableCatalog: string | null;
  fTableName: string | null;
  fTableSchema: string | null;
  srid: number | null;
  type: string | null;
}

export interface ItemContactRequests {
  acceptedAt: Timestamp | null;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  itemId: string;
  message: Generated<string>;
  ownerId: number;
  priceSnapshot: Generated<Numeric>;
  requesterId: number;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Items {
  availableNow: Generated<boolean>;
  category: Generated<ItemCategory>;
  contactMethod: Generated<string>;
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  id: string;
  latitude: number;
  longitude: number;
  name: string;
  ownerId: number;
  price: Generated<Numeric>;
  priceUnit: Generated<string>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Notifications {
  body: string;
  createdAt: Generated<Timestamp>;
  data: Generated<Json>;
  id: Generated<number>;
  readAt: Timestamp | null;
  title: string;
  type: Generated<string>;
  userId: number;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  provider: string;
  providerEmail: string;
  providerUserId: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: string;
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
}

export interface PushSubscriptions {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  identity: string;
  subscription: Json;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Requests {
  category: Generated<ItemCategory>;
  createdAt: Generated<Timestamp>;
  id: string;
  latitude: number;
  longitude: number;
  query: string;
  radiusM: Generated<number>;
  status: Generated<RequestStatus>;
  userId: number;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface SpatialRefSys {
  authName: string | null;
  authSrid: number | null;
  proj4text: string | null;
  srid: number;
  srtext: string | null;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  karma: Generated<number>;
  phone: Generated<string>;
  rating: Generated<Numeric>;
  role: Generated<string>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  geographyColumns: GeographyColumns;
  geometryColumns: GeometryColumns;
  itemContactRequests: ItemContactRequests;
  items: Items;
  loginAttempts: LoginAttempts;
  notifications: Notifications;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  pushSubscriptions: PushSubscriptions;
  requests: Requests;
  sessions: Sessions;
  spatialRefSys: SpatialRefSys;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const RequestStatusArrayValues: [RequestStatus, ...RequestStatus[]] = ["closed","matched","open"];
export const ItemCategoryArrayValues: [ItemCategory, ...ItemCategory[]] = ["creator","other","parts","tools","utility"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.